"""initial migrations

Revision ID: ba6c50a7a917
Revises: 105b3e623d20
Create Date: 2026-06-29 11:57:28.290961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba6c50a7a917'
down_revision: Union[str, Sequence[str], None] = '105b3e623d20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('location', sa.String(), nullable=True))
    op.execute(sa.text("UPDATE companies SET location = 'Unknown' WHERE location IS NULL"))
    op.alter_column('companies', 'location', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'location')
    # ### end Alembic commands ###
